/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package meteoapp2;

import org.junit.Test;
import static org.junit.Assert.assertTrue;

public class AppTest {
    
    @Test
    public void app() {
        // Assert statement
        assertTrue(true); // Esempio di un test semplice che passa sempre
    }
}