/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package meteoapp2;

import org.junit.Test;

import com.meteoapp2.Interfaccia;

import static org.junit.Assert.assertTrue;

import static org.junit.Assert.assertNotNull;
import javax.swing.ImageIcon;
import org.junit.Test;

public class InterfaceImageTest {

    @Test
    public void testIconsExistence() {
        // Verifica l'esistenza delle icone
        ImageIcon icon1 = new ImageIcon("/assets/background.jpg");
        ImageIcon icon2 = new ImageIcon("/assets/fog2.png");
        // Puoi aggiungere altri controlli per altre icone

        assertNotNull("Icon1 should not be null", icon1.getImage());
        assertNotNull("Icon2 should not be null", icon2.getImage());
        // Puoi aggiungere altri controlli per altre icone
    }

    @Test
    public void testImagesExistence() {
        // Verifica l'esistenza delle immagini
        ImageIcon image1 = new ImageIcon("assets/background.jpg");
        ImageIcon image2 = new ImageIcon("assets/fog2.png");
        // Puoi aggiungere altri controlli per altre immagini

        assertNotNull("Image1 should not be null", image1.getImage());
        assertNotNull("Image2 should not be null", image2.getImage());
        // Puoi aggiungere altri controlli per altre immagini
    }
}